version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka-server:
    image: wurstmeister/kafka:2.11-1.1.0
    privileged: true
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND: route -n | awk '/UG[ \t]/{print $$2}'
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: audit_test:1:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  active-mq:
    image: webcenter/activemq
    ports:
    - 8161:8161
    - 61616:61616
    - 5672:5672
    - 61613:61613
    - 1883:1883
    - 61614:61614
    environment:
    - ACTIVEMQ_STATIC_QUEUES=pacs.002.001.09.response.queue;pacs.008.001.07.request.queue
  
  router-db:
    image: mongo
    ports:
    - 27017:27017

  persistence-db:
    image: payment/persistencedb
    restart: always
    ports: 
    - 3306:3306

  persistance-service:
    image: payment/persistance-api
    links:
    - persistence-db:persistencedb
    ports:
    - 8192:8192

  validation-service:
    image: payment/validation-service
    ports:
    - 8083:8083

  transformation-service:
    image: payment/transformation-service
    ports:
    - 8090:8090

  router-service:
    image: payment/router-service
    links:
    - router-db:routerdb
    - active-mq:activemq
    - kafka-server:kafka
    - persistance-service:persistanceservice
    - validation-service:validationservice
    - transformation-service:transformationservice
    ports:
    - 8080:8080
    
  audit-service:
    image: payment/auditservice-consumer-kafka
    links:
    - router-db:routerdb
    - kafka-server:kafka
    - zookeeper:zookeeper
