version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.0-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  active-mq:
    image: webcenter/activemq
    ports:
    - 8161:8161
    - 61616:61616
    - 5672:5672
    - 61613:61613
    - 1883:1883
    - 61614:61614
    environment:
    - ACTIVEMQ_STATIC_QUEUES=pacs.002.001.09.response.queue;pacs.008.001.07.request.queue
  
  router-db:
    image: mongo
    ports:
    - 27017:27017

  persistence-db:
    image: payment/persistencedb
    restart: always
    ports: 
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=sourav
 
  router-service:
    image: payment/router-service
    links:
    - router-db:routerdb
    - active-mq:activemq
    ports:
    - 8080:8080

