active-mq:
  image: webcenter/activemq
  ports:
  - 8161:8161
  - 61616:61616
  - 5672:5672
  - 61613:61613
  - 1883:1883
  - 61614:61614
  environment:
  - ACTIVEMQ_STATIC_QUEUES=pacs.002.001.09.response.queue;pacs.008.001.07.request.queue
  
router-db:
  image: mongo
  ports:
  - 27017:27017

persistence-db:
  image: mysql:5.7
  restart: always
  ports: 
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=sourav
  - MYSQL_DATABASE=projectdb 
 
router-service:
  image: payment/router-service
  links:
  - router-db:routerdb
  - active-mq:activemq
  ports:
  - 8080:8080
